name: Build and deploy Next.js app to Azure Web App - PlayDevWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # This will create the .next directory

      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -R .next # Verify the contents of the .next directory
          if [ ! -d ".next" ]; then echo ".next directory not found!"; exit 1; fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: next-app
          path: .next # Ensure this path points to your build output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: next-app

      - name: Verify downloaded artifact
        run: |
          echo "Downloaded artifact contents:"
          ls -R next-app # Verify the contents of the downloaded artifact
          if [ ! -d "next-app" ]; then echo "Downloaded artifact not found!"; exit 1; fi

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'PlayDevWebApp'
          slot-name: 'Production'
          package: next-app # This should point to the artifact downloaded
